# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target 'TestRun' do
pod 'JSONModel'
pod 'RHAddressBook', '~> 1.1.0'
pod 'SIAlertView', '~> 1.3'
#pod 'MONActivityIndicatorView', '~> 0.0.1'
pod 'DejalActivityView'
pod 'MMPopLabel'
end

target 'TestRunTests' do

end